# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-23 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='NAME_MISSING', max_length=200)),
                ('LName', models.CharField(default='LName misssing', max_length=200)),
                ('Form', models.IntegerField(default=0)),
                ('Gender', models.IntegerField(default=0)),
                ('StudentID', models.IntegerField(default=0)),
            ],
        ),
    ]
